### ISSUE TITLE
As a user I want to see my class calendar

### ISSUE THREAD

**Issue by Alessandro100** [Alessandro100/concordia-campus-guide#145]

**Comment by wltrf** [comment]
Directions to my next class
- [ ] Connect to Google Calendar
- [ ] Be able to select among multiple calendarsc.
- [ ] Find the location of the classroom from the next Calendar Event

**Comment by wltrf** [comment]
Update: selects the calendar named "school" by default. Could add a settings options to change that when a settings page is implemented. Location is currently stored as a string e.g. "H-231". Would need a button that redirects to the directions page.
