### ISSUE TITLE
As a user, I want the transitions between displays of SGW and Loyola maps  to take  at most 1 sec upon request. 

### ISSUE THREAD

**Issue by taufiqueahmed** [Alessandro100/concordia-campus-guide#16]
After the toggle button has been clicked, the transition between the displays of one campus to another should take at most 1 sec.

**Comment by Alessandro100** [comment]
@razine-bensari Can you review my component? Im currently trying to setup the linter so all our code looks pretty but that will take a bit of time

**Comment by razine-bensari** [comment]
Doing the review, ill let you know in a few
