### ISSUE TITLE
As a student, I would like to know about important events taking place within either campuses.  

### ISSUE THREAD

**Issue by taufiqueahmed** [Alessandro100/concordia-campus-guide#21]
When a student clicks on a building, a pop-up screen is displayed and if there are any events for a given day, then events are displayed under the section called events.

**Comment by wltrf** [comment]
Displaying the events in the BottomDrawer (i.e. the popup when a user clicks a building) adds a lot of text and therefore clutters the interface. They will be left there for sprint 3 (lack of another location), but I suggest they should be removed for sprint 4 and a link to the future events page be added. See #143.
