### ISSUE TITLE
As a developer, I want a report describing the quality trends of my code (i.e. a quality report)

### ISSUE THREAD

**Issue by n-sheikh** [Alessandro100/concordia-campus-guide#78]
You must have SonarQube installed at this point.

Report metrics related to code duplication, code documentation, size, coupling, cohesion 
(coupling and cohesion are available only for object-oriented languages)

Report the code smells or technical debt detected by the tool

Describe your strategies to improve the metrics 

Comparison with previous metrics (metrics evolution) [optional for Sprint #3, only if you have metrics from Sprint #2, mandatory for Sprint #4]

**Comment by wltrf** [comment]
Integrated into jenkins pipeline for the master branch only. Can be viewed at server1.walterfleury.com:9000. Credentials sent in slack. So far, very few potential bugs and code smells which is good.

**Comment by wltrf** [comment]
Could be changed for staging branch as well in order to be able to fix some of the issues before releasing into master. @Alessandro100 let's talk about it next meeting.
